spring.application.name=CART SYSTEM

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cartdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=252252
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JWT Configuration
jwt.secret=9a4f4c35a5a5d5e5f5g5h5i5j5k5l5m5n5o5p5q5r5s5t5u5v5w5x5y5z1a2b3c4d5
jwt.expiration=86400000

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
